### ISSUE TITLE
Local labels

### ISSUE THREAD

**Issue by C-Elegans** [C-Elegans/d16#8]
In GNU as, it is possible to define local labels, which can be defined multiple times in the same file. They look similar to this

```
1:
sub r0,1
mov r3,2f ;loads the address of the first local label '2' defined after the instruction
jmp.ne 1b ;jumps to the first local label '1' defined before this instruction
2:
```

The only local labels are the numbers 0-9. 
The GNU as reference https://sourceware.org/binutils/docs/as/Symbol-Names.html

**Comment by flaviut** [comment]
fixed by 6f8406ee05b5f61398fd60f3ebed4eb0b07f6b8b
